Assignment (03/04/2026)

Assignment Name : NLP Mini App

Description : Build a chatbot, fake news detector, or keyword extractor.

----

Chosen Project: Keyword Extractor


In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

def extract_keywords(text):
    
    docs = [text]
    
    vectorizer = TfidfVectorizer(stop_words='english')
    X = vectorizer.fit_transform(docs)

    scores = zip(vectorizer.get_feature_names_out(), X.toarray()[0])
    
    sorted_words = sorted(scores, key=lambda x: x[1], reverse=True)
 
    return [word for word, score in sorted_words[:5]]


text = "Machine learning is a powerful tool in data science and artificial intelligence"

print("Keywords:", extract_keywords(text))

Keywords: ['artificial', 'data', 'intelligence', 'learning', 'machine']


-----------

Assignment (06/04/2026)

Assignment Name : Image as Numbers

Description : Load an image, print shape, pixel values, channels, and explain them.

In [7]:
import cv2
import numpy as np

img = cv2.imread("N.P.L Season 1_ Fiery showdown.png")

print("Image Shape:", img.shape)

print("\nSample Pixel Values:\n", img[0:5, 0:5])

b, g, r = cv2.split(img)

print("\nBlue Channel Sample:\n", b[0:5, 0:5])
print("\nGreen Channel Sample:\n", g[0:5, 0:5])
print("\nRed Channel Sample:\n", r[0:5, 0:5])

Image Shape: (1534, 1024, 3)

Sample Pixel Values:
 [[[ 24  37 101]
  [ 17  24  98]
  [ 16  23 104]
  [ 14  23 101]
  [ 17  25  92]]

 [[ 18  29 105]
  [ 19  25 107]
  [ 16  22 115]
  [ 14  23 113]
  [ 17  25  99]]

 [[ 15  26 107]
  [ 18  26 114]
  [ 17  30 128]
  [ 18  33 128]
  [ 18  28 103]]

 [[ 19  30 112]
  [ 17  24 118]
  [ 18  31 138]
  [ 21  38 137]
  [ 19  28 100]]

 [[ 19  28 114]
  [ 19  30 130]
  [ 21  39 152]
  [ 21  39 142]
  [ 19  29 102]]]

Blue Channel Sample:
 [[24 17 16 14 17]
 [18 19 16 14 17]
 [15 18 17 18 18]
 [19 17 18 21 19]
 [19 19 21 21 19]]

Green Channel Sample:
 [[37 24 23 23 25]
 [29 25 22 23 25]
 [26 26 30 33 28]
 [30 24 31 38 28]
 [28 30 39 39 29]]

Red Channel Sample:
 [[101  98 104 101  92]
 [105 107 115 113  99]
 [107 114 128 128 103]
 [112 118 138 137 100]
 [114 130 152 142 102]]


------

Assignment (08/04/2026)

Assignment Name : Image Filter Lab

Description : Use OpenCV to grayscale, blur, detect edges and show before/after.

In [ ]:
import cv2

img = cv2.imread("N.P.L Season 1_ Fiery showdown.png")

# Grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Blur (Gaussian Blur)
blur = cv2.GaussianBlur(gray, (5, 5), 0)

# Edge Detection (Canny)
edges = cv2.Canny(blur, 100, 200)

#Show images
cv2.imshow("Original Image", img)
cv2.imshow("Grayscale Image", gray)
cv2.imshow("Blur Image", blur)
cv2.imshow("Edge Detection", edges)

cv2.waitKey(0)
cv2.destroyAllWindows()

----------

Assignment (11/04/2026)

Assignment Name : Detection Brainstorm

Description : List 5 uses of face/object detection and design one solution.

----------

**Uses of Face/Object Detection**

1. Face Unlock in Smartphones

* Detects a user’s face to unlock the phone securely.

2. Attendance System

* Automatically detects and marks attendance using face recognition.

3. Traffic Monitoring

* Detects vehicles, traffic signals, and violations (like helmet detection).

4. Security Surveillance

* Identifies suspicious people or objects in public places like airports and malls.

5. Shopping & Retail

* Detects customer behavior, product movement, and shelf stock levels.

---

**Designed Solution**

**Smart Classroom Attendance System**

1. Problem

* Manual attendance takes time and may include errors or proxy attendance.

2. Solution

* Use **face detection** to automatically mark student attendance.

3. How it Works

1.Camera captures classroom image

2.System detects faces

3.Matches faces with stored student data

4.Marks attendance automatically

4. Technologies Used

* OpenCV
* Python
* Face Recognition models (CNN)

5. Expected Output

* Attendance list generated automatically
* Reduced manual effort
* Improved accuracy

